services:
  - type: web
    name: wildincas-feign-integration
    runtime: docker
    plan: free
    rootDir: spring-feign-integration
    dockerfilePath: ./Dockerfile
    healthCheckPath: /actuator/health
    envVars:
      - key: RESERVATIONS_API_URL
        value: https://backend-wildincas.onrender.com/api/reservations
